# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19ChS-0Wbmy8yLcv0l-uZEMRtR20dwBXt
"""

# Solicitar al usuario que ingrese la posición del hombre y la mujer en el tablero
columna_hombre = int(input("Ingresa la columna del hombre: "))
columna_mujer = int(input("Ingresa la columna de la mujer: "))

# Calcular la distancia entre el hombre y la mujer en términos de cuadros
distancia = abs(columna_hombre - columna_mujer)

# Mostrar la distancia en cuadros
print(f"La distancia entre el hombre y la mujer es de {distancia} cuadros.")

print("Maycol Andres Rueda")